# Generated by Django 2.1.5 on 2019-02-06 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liftit_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='vehicle_brand',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vehicle_type',
            name='description',
        ),
    ]
